export const FETCH_PRODUCTS_STARTED = "FETCH_PRODUCTS_STARTED";
export const FETCH_PRODUCTS_SUCCEEDED = "FETCH_PRODUCTS_SUCCEEDED";
export const FETCH_PRODUCTS_FAILED = "FETCH_PRODUCTS_FAILED";

export const SAVE_PRODUCT_STARTED = "SAVE_PRODUCT_STARTED";
export const CREATE_PRODUCT_SUCCEEDED = "CREATE_PRODUCT_SUCCEEDED";
export const UPDATE_PRODUCT_SUCCEEDED = "UPDATE_PRODUCT_SUCCEEDED";
export const SAVE_PRODUCT_FAILED = "SAVE_PRODUCT_FAILED";
export const DELETE_PRODUCT = "DELETE_PRODUCT";